version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: timesheet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheetdb
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql

  app:
    build: .
    container_name: timesheet-app
    depends_on:
      - mysql
    ports:
      - "8089:8089"

volumes:
  timesheetvol:
